name:                hs-demo
version:             0.1.0.0
github:              "githubuser/hs-demo"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-demo#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- scotty
- text
- wai-extra
- uuid

library:
  source-dirs: src

executables:
  serving-ping:
    main:                serving-handlers/Ping.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-demo

  serving-pong:
    main:                serving-handlers/Pong.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-demo


  events-ping:
    main:                event-handlers/OnPing.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-demo

  events-pong:
    main:                event-handlers/OnPong.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-demo

tests:
  hs-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-demo
