FROM haskell:9.0.2-slim-buster

WORKDIR /app

COPY stack.yaml .
COPY package.yaml .
RUN stack build --system-ghc --only-dependencies

# ---

COPY event-handlers event-handlers
COPY serving-handlers serving-handlers
COPY src src
COPY test test

RUN stack install --system-ghc --copy-bins
