FROM ghcr.io/openfaas/of-watchdog:0.9.3 as watchdog
FROM haskell:8.10.7-slim-buster as builder

FROM debian:buster-slim

ARG EXE_PATH=undefined

COPY ${EXE_PATH} /root/app-exe
RUN chmod +x /root/app-exe

EXPOSE 8080

CMD ["/root/app-exe"]
